# fly.toml app configuration file generated for cirkl-ai on 2025-09-20T23:13:34-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cirkl-ai'
primary_region = 'bos'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 9501
  force_https = true
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
